# This is a basic workflow to help you get started with Actions

name: Upload Artifact

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: sudo mkdir -p "${pwd}/sample-art"
      - run: sudo bash -c 'echo "hello" > ${pwd}/sample-art/hello.txt'
      - run: ls -l
      - run: ls ${pwd}/sample-art/
      - uses: actions/upload-artifact@v2
        with:
          name: sample-art
          path: ${pwd}/sample-art/hello.txt
          retention-days: 5
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: 'sample-art'
          path: $pwd/sample-art/hello.txt
